const versions = [
    {
        id: 0,
        label: "Official Game",
        description: "Current official points for organized play.",
        pointDeltas: {},
        omittedCards: []
    },
    {
        id: 1,
        label: "Random Changes XDDD",
        description: "Totally for funsies changes",
        pointDeltas: {
            'nk': -2,
            'nm': -2,
            'nn': -2,
            'no': 2,
            'nr': -2,
            'nv': -2,
            'na': -2,
            'nc': -1,
            'ne': -4,
            'nf': -2,
            'mt': -5,
            'mu': 2,
            'mv': 1,
            'mx': -4,
            'mj': -1,
            'mn': -1,
            'mo': -3,
            'tb': -1,
            'lp': -3,
            'lv': -1,
            'lk': -2,
            'll': -2,
            'rk': 2,
            'li': -1,
            'ld': -1,
            'lh': -1,
            'me': -3,
            'mf': 1,
            'mh': -1,
            'sq': 1,
            'sr': 1,
            'ji': -2,
            'jp': 1,
            'jq': -2,
            'js': -1,
            'jx': -1,
            'jz': -1,
            'ka': -2,
            'kc': -1,
            're': 1,
            'rf': -3,
            'rj': -1,
            'sw': 2,
            'ro': -2,
            'ru': -2,
            'kl': -3,
            'kp': -1,
            'kt': -1,
            'ku': 1,
            'kw': -1,
            'ja': -4,
            'on': -2,
            'pj': 4,
            'pa': -2,
            'pd': -4,
            'pl': -1,
            'oq': -2,
            'pz': -3,
            'oy': -2,
            'qf': 5,
            'qg': -2,
            'oi': -2,
            'qs': -1,
            'oo': -6,
            'ny': -2,
            'qb': -1,
            'ot': -1,
            'az': -4,
            'au': 1,
            'be': 2,
            'bi': 2,
            'bl': -4,
            'bn': -4,
            'bd': -4,
            'bb': -4,
            'bk': -6,
            'bm': -6,
            'ca': -2,
            'cc': -4,
            'by': -4,
            'bw': -5,
            'cd': -3,
            'br': -8,
            'cg': -5,
            'ad': -5,
            'ae': -3,
            'ai': -5,
            'ac': -2,
            'es': -1,
            'eu': -2,
            'ew': -3,
            'ey': -2,
            'ez': 1,
            'fb': -1,
            'fc': -5,
            'ej': -1,
            'el': -1,
            'gd': -1,
            'gf': -1,
            'gh': -3,
            'gk': -2,
            'gl': -2,
            'gw': -3,
            'fk': -1,
            'fo': -2,
            'fu': -1,
            'fv': -2,
            'fw': -1,
            'hd': -1,
            'hh': -3,
            'hi': -2,
            'hj': -4,
            'hk': -3,
            'hr': -2,
            'hs': 2,
            'ht': -2,
            'hu': -3,
            'hv': -1,
            'hl': -1
        },
        omittedCards: [
            
        ]
    }
];

export default versions