/*
    pointDeltas are cards that get a point change
    omittedCards is how to hide cards from the "everyone" role, note: any cards NOT in this field will be visible to the public
    enabledCards is only to show what cards are being added to that "version", note: this field doesn't actuall do anything, its cosmetic and convenient
*/

const versions = [
    {
        id: 0,
        label: "Official Game",
        description: "Current official points for organized play.",
        roles: ["everyone"],
        pointDeltas: {},
        footnoteChanges: {},
        omittedCards: [
            "tg",
            "gp",
            "th",
            "ti",
            "tj",
            "tk"
        ],
        enabledCards: []
    },
    {
        id: 1,
        label: "ARC Core Playtesting",
        description: "Playtesting package for Core members",
        roles: ["core"],
        pointDeltas: {
            "az": -4,
            "bl": -5,
            "bn": -5,
            "bd": -4,
            "bb": -4,
            "sv": -8,
            "pj": 3,
            "pa": -2,
            "pz": -3,
            "ou": 2,
            "fc": -5,
            "eu": -2,
            "ez": 1,
            "ey": -2,
            "ej": -1,
            "el": -1,
            "cg": -5,
            "ca": -2,
            "cc": -4,
            "bp": -2,
            "il": -2,
            "in": -2,
            "oy": -2,
            "qf": 4,
            "qg": -2,
            "oo": -5,
            "oi": -2,
            "rk": 3,
            "gc": 3,
            "gk": -2,
            "gl": -2,
            "gh": -3,
            "gw": -2,
            "fy": -2,
            "fk": -1,
            "fo": -2,
            "am": -2,
            "ak": -3,
            "al": -2,
            "sx": -4,
            "iy": -6,
            "qb": -2,
            "li": -1,
            "hh": -2,
            "hj": -3,
            "hd": -1,
            "ab": -2,
            "ah": -3,
            "ai": -8,
            "ac": -3,
            "ja": -4,
            "jb": -3,
            "ot": -1,
            "pm": -2,
            "hr": -2,
            "hv": -1,
            "ji": -2,
            "jq": -2,
            "js": -1,
            "me": -2,
            "lh": -1,
            "mt": -5,
            "mx": -4,
            "na": -2,
            "nc": -1,
            "ne": -4,
            "nf": -2,
            "ng": 2,
            "nm": -2,
            "nn": -2,
            "nv": -3,
            "nj": -1,
            "ss": -2,
            "mb": 1  
        },
        footnoteChanges: {
            "ta": ["+ Rogue"],
            "ht": ["+ Rogue"],
            "hl": ["+ Rogue"],
            "tg": ["Added to CIS"],
            "gp": ["Added to CIS"]
        },
        omittedCards: [],
        enabledCards: []
    },
    {
        id: 2,
        label: "ARC Playtesting",
        description: "Playtesting package",
        roles: ["core", "playtester"],
        pointDeltas: {},
        footnoteChanges: {},
        omittedCards: [],
        enabledCards: []
    }
];

export default versions